// Render results/results.json as TABLE.md: one row per Guitar Pro version,
// one column per reader, and beneath it every file a reader got wrong or
// couldn't open. Unverified files are counted in their cell but not listed:
// there is nothing to say about them yet beyond how many there are.
//
//   node harness/render.mjs

import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { FORMATS } from "./files.mjs"
import { RESULTS } from "./judge.mjs"

const ROOT = path.resolve(import.meta.dirname, "..")
const TABLE = path.join(ROOT, "TABLE.md")

const MARK = {
	full: "✅ Full",
	partial: "⚠️ Partial",
	fails: "❌ Fails",
	unsupported: "— Not supported",
	unverified: "❔ Unverified",
}

/**
 * One cell: how a tool did on every file of one version.
 *
 * A cell is only as good as its worst verified file — "Full" means every file
 * that could be checked was read completely. Unverified files are counted but
 * never decide the level, in either direction.
 */
export const summarizeCell = verdicts => {
	const count = verdict => verdicts.filter(v => v.verdict === verdict).length
	const total = verdicts.length
	const unverified = count("unverified")
	const verified = total - unverified - count("unsupported")
	if (total === 0) return { level: null, text: "" }
	if (count("unsupported") === total) return { level: "unsupported", text: MARK.unsupported }
	if (verified === 0) return { level: "unverified", text: `${MARK.unverified} (${total} files)` }

	const full = count("full")
	const opened = full + count("partial")
	const level = full === verified ? "full" : opened === 0 ? "fails" : "partial"
	const detail = level === "full" ? `${full} files` : `${full} of ${verified} files full`
	const pending = unverified ? `, ${unverified} unverified` : ""
	return { level, text: `${MARK[level]} (${detail}${pending})` }
}

const fileLink = file =>
	file.tier === "public"
		? `[${file.source.path.split("/").pop()}](${file.source.url})`
		: `\`${file.id}\` (private)`

const describe = (verdict, checks) => {
	if (verdict.verdict === "fails") return `${MARK.fails}: ${verdict.reason}`
	const names = verdict.checks.map(id => checks.find(c => c.id === id).label.toLowerCase())
	return `${MARK[verdict.verdict]}: ${names.join(", ")}`
}

export const render = results => {
	const { tools, files, checks } = results
	const date = results.measuredAt.slice(0, 10)
	const rows = FORMATS.filter(format => files.some(f => f.format === format.id))

	const header = `| Version | ${tools.map(t => `[${t.name}](${t.homepage}) ${t.version}`).join(" | ")} |`
	const rule = `|---|${tools.map(() => "---").join("|")}|`
	const body = rows.map(format => {
		const ofFormat = files.filter(f => f.format === format.id)
		const cells = tools.map(tool => summarizeCell(ofFormat.map(f => f.verdicts[tool.id])).text)
		return `| ${format.label} | ${cells.join(" | ")} |`
	})

	const exceptions = rows.flatMap(format => {
		const lines = files
			.filter(f => f.format === format.id)
			.flatMap(file =>
				tools
					.filter(tool => ["partial", "fails"].includes(file.verdicts[tool.id].verdict))
					.map(tool => `| ${fileLink(file)} | ${tool.name} | ${describe(file.verdicts[tool.id], checks)} |`),
			)
		if (!lines.length) return []
		return [`### ${format.label}`, "", "| File | Reader | Result |", "|---|---|---|", ...lines, ""]
	})

	const counted = tier => files.filter(f => f.tier === tier).length
	return [
		"<!-- Generated by harness/render.mjs from results/results.json. Do not edit by hand. -->",
		"",
		"# Guitar Pro compatibility",
		"",
		`Measured ${date} on ${files.length} files (${counted("public")} public, ${counted("private")} private). ` +
			"How each result was reached is in the [methodology](README.md#methodology).",
		"",
		header,
		rule,
		...body,
		"",
		"✅ every checked file read completely · ⚠️ some files opened but came out wrong · " +
			"❌ files that should open didn't · — a version the reader doesn't claim to support · " +
			"❔ nothing to check it against yet",
		"",
		"## Files read wrongly or not at all",
		"",
		exceptions.length ? exceptions.join("\n") : "None.\n",
		"Results licensed [CC BY 4.0](LICENSE-RESULTS): cite as “Melodist Studio, Guitar Pro compatibility, " +
			`measured ${date}”.`,
		"",
	].join("\n")
}

const main = () => {
	writeFileSync(TABLE, render(JSON.parse(readFileSync(RESULTS, "utf8"))))
	console.log(`wrote ${path.relative(ROOT, TABLE)}`)
}

if (process.argv[1] === import.meta.filename) main()
